title: Bay Yang Jie
description: Master's student | SUSS | Analytics and Visualization 
logo: https://github.com/bayyangjie/bayyangjie.github.io/blob/main/profile_pictures/IMG_1788%20copy.jpg?raw=true
linkedin: https://linkedin.com/in/yang-jie-bay
show_downloads: true
theme: jekyll-theme-minimal
